package james.meadows.hri.gui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;

import javax.swing.AbstractAction;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Toolbar {

	private DocumentationGUI gui;
	private JFrame frame;
	
	public Toolbar(DocumentationGUI gui) {
		this.gui = gui;
		this.frame = gui.getFrame();

		this.setupPanel();
	}

	private void setupPanel() {
		JPanel west = new JPanel();
		west.setLayout(new BoxLayout(west, BoxLayout.PAGE_AXIS));
		JMenuBar menuBar = new JMenuBar();
		setupFileMenu(menuBar);
		
		frame.setJMenuBar(menuBar);
		frame.add(west, BorderLayout.WEST);
	}

	@SuppressWarnings("serial")
	private void setupFileMenu(JMenuBar menu) {
		JMenu fileMenu = new JMenu("File");
		menu.add(fileMenu);
		
		JMenuItem newFile = new JMenuItem("New");
		newFile.addActionListener(new AbstractAction() {

			@Override
			public void actionPerformed(ActionEvent e) {
				new NewProject(gui);
			}			
		});
		fileMenu.add(newFile);
		
		JMenuItem export = new JMenuItem("Export");
		export.addActionListener(new AbstractAction() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (gui.getDocumentation() == null) {
					JOptionPane.showMessageDialog(null, "Nothing to export. Load a project first");
					return;
				}
				gui.getDocumentation().saveToExcel();
				JOptionPane.showMessageDialog(null, "Export Complete. Saved to Excel as Autogenerated in program directory");
			}			
		});
		fileMenu.add(export);
		
		JMenu projectMenu = new JMenu("Project");
		menu.add(projectMenu);
		
		JMenuItem render = new JMenuItem("Render");
		render.addActionListener(new AbstractAction() {

			@Override
			public void actionPerformed(ActionEvent e) {
				new RenderedView(gui);
			}			
		});
		projectMenu.add(render);
		
		JMenuItem search = new JMenuItem("Search");
		search.addActionListener(new AbstractAction() {

			@Override
			public void actionPerformed(ActionEvent e) {
				JOptionPane.showMessageDialog(null, "This button doesn't do anything yet.");
			}			
		});
		projectMenu.add(search);
	
		JMenu about = new JMenu("About");
		menu.add(about);
		
		JMenuItem license = new JMenuItem("License");
		license.addActionListener(new AbstractAction() {

			@Override
			public void actionPerformed(ActionEvent e) {
				JOptionPane.showMessageDialog(null, "Oh no. Your free trial is expiring soon");
			}			
		});
		about.add(license);
	}
}
